name: build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Pack
        run: dotnet pack src/Bidkee.Client/Bidkee.Client.csproj -c Release -o ./nupkg

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: bidkee

      - name: Push
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
            --api-key ${{ steps.login.outputs.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json \
            --skip-duplicate